from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

backup=Path('archive/index-before-premium-v5.html')
backup.parent.mkdir(parents=True,exist_ok=True)
if not backup.exists(): backup.write_text(s,encoding='utf-8')

s=s.replace('당신의 일상에<br>볼보가 함께할 때,','당신에게 맞는 볼보를<br>더 쉽게.')
s=s.replace('안전은 기본이 되고, 삶은 더 특별해집니다.','복잡한 사양표보다, 내 생활에 맞는 선택이 먼저입니다.')
s=s.replace('스칸디나비안 프리미엄의 가치.<br>복잡한 정보는 쉽게, 필요한 내용은 정확하게 안내해드립니다.','모델 선택부터 트림 비교, 시승과 출고 이후까지.<br>필요한 정보만 쉽고 정확하게 안내해드립니다.')
s=s.replace('<div class="actions"><a class="btn light" href="#lineup">모델 라인업 살펴보기 →</a><button class="btn" onclick="alert(\'브랜드 영상은 다음 업데이트에서 연결됩니다.\')">▶ 브랜드 영상 보기</button></div>','<div class="actions"><a class="btn light" href="#lineup">내게 맞는 볼보 찾기</a><a class="btn" href="http://qr.kakao.com/talk/2LfLSm9DLJcfVv19vfXeS5R1AHQ-" target="_blank" rel="noopener">카카오톡 상담</a></div>')

profile='''<aside class="profile compact-profile" id="contact"><img src="assets/img03.webp" alt="이민웅 Sales Consultant"><div class="pb"><small>VOLVO SALES CONSULTANT</small><h3>이민웅</h3><p>차를 고르는 순간부터 출고 이후까지,<br>필요한 내용을 쉽고 정확하게 안내합니다.</p><div class="profile-actions"><a class="contact" href="tel:01026503211">전화 상담</a><a class="contact kakao" href="http://qr.kakao.com/talk/2LfLSm9DLJcfVv19vfXeS5R1AHQ-" target="_blank" rel="noopener">카카오톡</a></div></div></aside>'''
s=re.sub(r'<aside class="profile(?: compact-profile)?" id="contact">.*?</aside>',profile,s,count=1,flags=re.S)

category='''<div class="category-showcase" aria-label="볼보 바디타입 선택"><button class="category-card active" data-filter="suv" onclick="filterCategory('suv',this)"><span class="cat-kicker">VOLVO SUV</span><strong>SUV</strong><small>도심형 XC40부터 플래그십 XC90까지</small><span class="cat-arrow">차량 보기 →</span></button><button class="category-card" data-filter="electric" onclick="filterCategory('electric',this)"><span class="cat-kicker">PURE ELECTRIC</span><strong>ELECTRIC</strong><small>EX30 · EX90 · ES90, 전동화 라이프스타일</small><span class="cat-arrow">차량 보기 →</span></button><button class="category-card" data-filter="sedan" onclick="filterCategory('sedan',this)"><span class="cat-kicker">VOLVO SEDAN</span><strong>SEDAN</strong><small>정숙함과 편안함을 위한 S90</small><span class="cat-arrow">차량 보기 →</span></button></div><div class="model-list-head"><div><span>SELECTED MODELS</span><h3 id="selectedCategoryTitle">SUV 라인업</h3></div><button onclick="filterCategory('all',this)">전체 모델 보기</button></div>'''
if 'category-showcase' not in s:
    s=s.replace('<div class="models">',category+'<div class="models" id="modelGrid">',1)
elif 'id="modelGrid"' not in s:
    s=s.replace('<div class="models">','<div class="models" id="modelGrid">',1)

floating='''<div class="floating-contact" aria-label="빠른 상담"><div class="floating-person"><img src="assets/img03.webp" alt=""><span><b>이민웅</b><small>Volvo Sales Consultant</small></span></div><a href="tel:01026503211">전화 상담</a><a class="fkakao" href="http://qr.kakao.com/talk/2LfLSm9DLJcfVv19vfXeS5R1AHQ-" target="_blank" rel="noopener">카카오톡 상담</a></div>'''
if 'floating-contact' not in s: s=s.replace('</body>',floating+'</body>')

css='''
/* PREMIUM-V5-START */
:root{--ink:#07131d;--paper:#f5f6f4;--soft:#e9edee;--line:#d8dddf;--accent:#0a1722}
body{background:var(--paper);letter-spacing:-.02em;padding-bottom:78px}.top{height:76px;padding:0 max(28px,4.5vw);gap:34px;background:rgba(7,19,29,.96);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.09)}.top img{width:48px;height:48px}.nav{gap:30px;font-size:12px}.nav a{opacity:.8}.nav a:hover{opacity:1}.cta{padding:11px 18px;border-color:#ffffff52;font-size:12px}
.hero{min-height:650px;grid-template-columns:minmax(0,1fr) 285px;background-position:center;background-size:cover;overflow:hidden}.hero:after{background:linear-gradient(90deg,rgba(4,14,23,.91) 0%,rgba(4,14,23,.78) 35%,rgba(4,14,23,.25) 68%,rgba(4,14,23,.12) 100%)}.copy{padding:92px max(34px,6vw);max-width:850px}.ey{font-size:10px;letter-spacing:.28em;color:#e7ebed}.copy h1{font-family:Arial,'Malgun Gothic',sans-serif;font-size:clamp(48px,5vw,78px);line-height:1.04;font-weight:300;letter-spacing:-.065em;margin:22px 0 24px}.copy p{font-size:16px;color:rgba(255,255,255,.94)}.copy .note{margin-top:28px;max-width:590px;padding-top:20px;border-color:rgba(255,255,255,.28);font-size:12px;line-height:1.9;color:rgba(255,255,255,.72)}.actions{margin-top:30px;gap:10px}.btn{padding:14px 21px;font-size:11px;border-color:rgba(255,255,255,.45)}.btn.light{background:#fff;color:#07131d}
.compact-profile{width:255px;align-self:end;margin:0 4vw 42px 0;border-radius:20px;background:rgba(255,255,255,.96);box-shadow:0 28px 80px rgba(0,0,0,.22);display:grid;grid-template-columns:82px 1fr;align-items:center;padding:13px;overflow:visible}.compact-profile img{width:82px;height:104px;object-fit:cover;border-radius:13px}.compact-profile .pb{padding:4px 3px 4px 13px;text-align:left}.compact-profile .pb small{font-size:8px;letter-spacing:.1em}.compact-profile .pb h3{font-size:20px;margin:3px 0 5px}.compact-profile .pb p{font-size:9px;margin:0;color:#657078;line-height:1.5}.profile-actions{display:flex;gap:5px;margin-top:9px}.profile-actions .contact{margin:0;padding:7px 8px;font-size:8px;white-space:nowrap}.profile-actions .kakao{color:#111}
.section{padding:64px max(28px,4vw) 28px}.line{display:block;max-width:1440px;margin:0 auto}.intro{background:none;padding:0 0 30px;border-radius:0;display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid #d9dede}.intro .ey{color:#6b777e}.intro h2{font-size:40px;font-weight:400;letter-spacing:-.05em;margin:8px 0 0}.intro p{max-width:340px;text-align:right;font-size:12px;line-height:1.7;margin:0}
.category-showcase{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:28px 0 22px}.category-card{border:1px solid #d8dddf;background:#fff;border-radius:18px;padding:28px 26px;text-align:left;min-height:175px;cursor:pointer;transition:.24s;color:#111922}.category-card:hover{transform:translateY(-3px);box-shadow:0 18px 42px rgba(7,19,29,.08)}.category-card.active{background:#0a1722;color:#fff;border-color:#0a1722}.cat-kicker{display:block;font-size:8px;letter-spacing:.22em;opacity:.58;margin-bottom:28px}.category-card strong{display:block;font-size:30px;font-weight:500}.category-card small{display:block;font-size:10px;opacity:.68;margin-top:7px}.cat-arrow{display:block;font-size:9px;margin-top:20px;font-weight:700}.model-list-head{display:flex;justify-content:space-between;align-items:end;padding:15px 0 13px}.model-list-head span{font-size:8px;letter-spacing:.2em;color:#7a858b}.model-list-head h3{font-size:22px;font-weight:500;margin:5px 0 0}.model-list-head button{border:0;background:transparent;font-size:10px;text-decoration:underline;text-underline-offset:4px;cursor:pointer;color:#5d6970}
.models{grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.model{min-height:340px;border-radius:17px;background:#dce1e2;transition:.25s}.model:hover{transform:translateY(-3px)}.model:after{background:linear-gradient(180deg,transparent 42%,rgba(4,13,20,.88) 100%)}.mb{text-align:left;padding:24px}.mb h3{font-size:25px;font-weight:500}.mb small{font-size:8px;letter-spacing:.1em;opacity:.72}.mini{justify-content:flex-start;margin-top:13px}.mini button{padding:7px 10px;background:rgba(255,255,255,.08);font-size:8px}
.values{max-width:1440px;margin:34px auto 22px;border-radius:18px;border:1px solid #e0e4e5}.vh,.val{padding:30px 24px}.vh h2{font-weight:400}.val b{font-size:12px;margin-top:10px}.val small{line-height:1.6}.tools{max-width:1440px;margin:0 auto;padding:8px 0 42px;grid-template-columns:repeat(3,1fr);gap:12px}.tile{min-height:250px;border-radius:18px;padding:28px}.tile:before{background-position:center;background-size:cover}.tile:after{background:linear-gradient(90deg,rgba(5,16,25,.92) 0%,rgba(5,16,25,.62) 48%,rgba(5,16,25,.12) 100%)}.tile h3{font-size:24px;font-weight:500}.tile p{font-size:11px;line-height:1.6}.tile button{margin-top:14px;padding:10px 14px}.quick{grid-column:1/-1;border:1px solid #e0e4e5;border-radius:15px;flex-direction:row;align-items:center;justify-content:center;gap:22px;padding:14px;background:rgba(255,255,255,.75)}
.service{max-width:1440px;margin:0 auto 42px;border-radius:20px;padding:38px;border:1px solid #e0e4e5}.sh h2{font-size:34px;font-weight:400}.regions{gap:8px}.regions button{padding:11px;background:#fff}.sr{padding:20px;border-radius:14px}.footer{padding:24px max(28px,4vw);background:#07131d;color:rgba(255,255,255,.72)}
.floating-contact{position:fixed;z-index:90;left:50%;bottom:14px;transform:translateX(-50%);width:min(720px,calc(100% - 28px));height:58px;padding:7px 8px 7px 11px;border-radius:18px;background:rgba(7,19,29,.95);backdrop-filter:blur(18px);box-shadow:0 18px 50px rgba(0,0,0,.25);display:flex;align-items:center;gap:8px;color:#fff;border:1px solid rgba(255,255,255,.13)}.floating-person{display:flex;align-items:center;gap:9px;margin-right:auto}.floating-person img{width:38px;height:38px;border-radius:11px;object-fit:cover}.floating-person span{display:flex;flex-direction:column}.floating-person b{font-size:11px}.floating-person small{font-size:8px;opacity:.6}.floating-contact>a{padding:11px 15px;border:1px solid rgba(255,255,255,.22);border-radius:12px;font-size:9px;font-weight:800}.floating-contact .fkakao{background:#fee500;color:#111;border-color:#fee500}
@media(max-width:1050px){.hero{grid-template-columns:1fr}.compact-profile{position:absolute;right:0;bottom:0}.models{grid-template-columns:repeat(2,1fr)}.tools{padding-left:4vw;padding-right:4vw}.service{margin-left:4vw;margin-right:4vw}.values{margin-left:4vw;margin-right:4vw}}
@media(max-width:700px){body{padding-bottom:70px}.top{height:62px;padding:0 18px}.top img{width:40px;height:40px}.hero{min-height:650px;display:block;background-position:60% center}.hero:after{background:linear-gradient(180deg,rgba(4,14,23,.46) 0%,rgba(4,14,23,.70) 55%,rgba(4,14,23,.92) 100%)}.copy{padding:64px 25px 210px}.copy h1{font-size:44px;line-height:1.05}.copy p{font-size:14px}.copy .note{font-size:10px}.compact-profile{left:20px;right:20px;bottom:24px;width:auto;margin:0;grid-template-columns:72px 1fr;padding:10px}.compact-profile img{width:72px;height:90px}.section{padding:42px 18px 18px}.intro{display:block}.intro h2{font-size:32px}.intro p{text-align:left;margin-top:10px}.category-showcase{grid-template-columns:1fr;gap:8px;padding-top:20px}.category-card{min-height:125px;padding:20px}.cat-kicker{margin-bottom:14px}.category-card strong{font-size:25px}.models{grid-template-columns:1fr}.model{min-height:360px}.values{margin:25px 18px 15px;grid-template-columns:1fr 1fr}.vh{grid-column:1/-1}.tools{padding:5px 18px 25px;grid-template-columns:1fr}.tile{min-height:220px}.quick{grid-column:auto;justify-content:flex-start;overflow:auto}.service{margin:0 18px 28px;padding:24px}.floating-contact{bottom:8px;height:54px;width:calc(100% - 16px);border-radius:16px}.floating-person small{display:none}.floating-contact>a{padding:10px 11px;font-size:8px}}
/* PREMIUM-V5-END */
'''
s=re.sub(r'/\* PREMIUM-V5-START \*/.*?/\* PREMIUM-V5-END \*/','',s,flags=re.S)
s=s.replace('</style>',css+'</style>',1)

js='''<script id="premium-v5-js">function filterCategory(cat,button){const map={XC40:'suv',XC60:'suv',XC90:'suv',EX30:'electric',EX90:'electric',ES90:'electric',S90:'sedan'};document.querySelectorAll('.category-card').forEach(b=>b.classList.toggle('active',b.dataset.filter===cat));document.querySelectorAll('#modelGrid .model').forEach(card=>{const name=card.querySelector('h3')?.textContent.trim()||'';card.style.display=(cat==='all'||map[name]===cat)?'block':'none'});const title={suv:'SUV 라인업',electric:'순수 전기 라인업',sedan:'세단 라인업',all:'볼보 전 라인업'}[cat]||'볼보 라인업';const el=document.getElementById('selectedCategoryTitle');if(el)el.textContent=title}document.addEventListener('DOMContentLoaded',()=>filterCategory('suv',document.querySelector('.category-card[data-filter="suv"]')));</script>'''
s=re.sub(r'<script id="premium-v5-js">.*?</script>','',s,flags=re.S)
s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
